### ISSUE TITLE
[Training] Create First PR and Implement TourOfHeroes.

### ISSUE THREAD

**Issue by vn-taibh** [vn-taibh/training-ang-thaipt#4]
Ref: [Angular Tutorial](https://angular.io/tutorial/toh-pt1)

---
## Task:
- [ ] Create First PR.
    - Base from branch `feature/angular`.
    - Ref: #5 
- [ ] Implement TourOfHeroes.
    - [ ] Create The hero editor.
        - [ ] Create the heroes component.
        - [ ] Show heroes component view.
        - [ ] Show the hero object with hero class.
        - [ ] Edit the heroes.
    - [ ] Display the heroes list
        - [ ] Create mock heroes.
        - [ ] Display list hero.
        - [ ] Handle click event.
        - [ ] Style the hero. (selected, empty).
    - [ ] Detail Component.
        - [ ] Create hero detail component.
        - [ ] Show hero detail component.
        - [ ] Handle hero detail.
