### ISSUE TITLE
[Training][Angular] Services - Routing - HTTP

### ISSUE THREAD

**Issue by vn-taibh** [vn-taibh/training-ang-thaipt#7]
Ref: [Docs](https://angular.io/tutorial/toh-pt4)

---
## Task:
- [ ] Services .
    - Create the HeroService.
    - Apply HeroService to HeroesComponent.
- [ ] Routing.
    - [ ] Add the AppRoutingModule.
    - [ ] Add RouterOutlet
    - [ ] Add a navigation link.
    - [ ] Add a dashboard view.
    - [ ] Navigating to hero details.
    - [ ] Display the heroes list
    - [ ] Routable HeroDetailComponent.
 - [ ] HTTP.
    - [ ] Enable HTTP services.
    - [ ] Simulate a data server (You can use mock api: [Api](http://5c321fcafe034a001404dcb8.mockapi.io/api/v1/Heroes)).
    - [ ] Heroes and HTTP.
    - [ ] Update heroes
    - [ ] Add a new hero
    - [ ] Delete a hero
    - [ ] Search by name
